sudo: required

language: elixir

services:
  - docker

cache:
  directories:
  - deps
  - _build

env:
  - MIX_ENV=test

install:
  - docker-compose up -d db
  - docker-compose run api mix deps.get

script:
  - docker-compose run api mix credo --strict
  - docker-compose run api mix test